Fix/report card unities
ipti/br.tag pull request #614
Opened 2024-02-05 15:28 UTC by Gusta-Santos

## Motivação
Foi necessário corrigir pequenas coisas nas telas de lançamento de notas, para que não ocorram erros durante a utilização das telas.

## Alterações Realizadas
- Corrigindo a disposição de unidades de lançamento de notas de búzios
- Permitindo que sejam adicionadas notas maiores de 10 em lançamento de notas
- Adicionada a verificação de recuperação final em lançamento de notas

## Fluxo de Teste

Na tela de lançamento de notas de búzios
```
Entrar na tela
Testar com turma que possua menos de 3 unidades
```

Na tela de lançamento de notas
```
Entrar na tela
Testar adicionar notas maiores de 10
Testar turmas que possuam recuperação final e verificar se esse campo aparece
```

## Migrations Utilizadas
Nenhuma migration foi utilizada

## Checklist de revisão
- [x] O número da versão foi alterado no arquivo ``` config.php ```?
- [x] Foi adicionada uma descrição das alterações no arquivo de   ``` CHANGELOG ```?
- [ ] O pull request passou na avaliação do SonarLint?
- [ ] O pull request está nomeado corretamente seguindo o padrão de nomes de branchs?

2024-02-07 14:11 UTC, evellynreis approved these changes
Foram feitos os testes e tudo estar funcionando conforme o esperado. Pull aprovado!

2024-02-07 15:03 UTC, AnotherOne07 approved these changes
Fluxo de teste realizado e resultado esperado obtido com sucesso!
É possível inserir notas acima de 10, e para turmas que possuem uma etapa onde a estrutura de avaliação possui recuperação, o campo aparece assim como esperado, para aquelas que não possuem o campo não é apresentado na tela.

2024-02-18 22:36 UTC, igorgoncalves requested changes
FALHA NA VERIFICAÇÃO DO SNYK, $_POST DIRETO NO PARAMETRO PODE SER INSEGURO, LEIA  DESCRIÇÃO DO ERRO PARA ENTENDER COMO CORRIGIR

2024-02-27 15:06 UTC, igorgoncalves approved these changes

2024-02-27 15:06 UTC, merged