Fix/class turn
ipti/br.tag pull request #683
Opened 2024-04-15 18:52 UTC by nathanipti

## Motivação
Foi identificado que, nas inconsistências, o ID da classe estava sendo associado a outro ID incorreto.

## Alterações Realizadas
Foi implementado uma correção para armazenar o ID correto da classe.

## Fluxo de Teste

### `🧪 Teste 01`

1. Acesse o menu "Turmas".
2. Escolha uma turma específica.
3. Vá para a seção "Turno".
4. Selecione a opção "Selecione o Turno".
5. Salve as alterações.
6. Navegue até "Integrações" -> "Sagres".
7. Selecione o mês atual.
8. Certifique-se de marcar a opção para "Gerar arquivo excluindo alunos sem CPF".
9. Clique em "Exportar Unidade".

Verifique as inconsistências reportadas. Se uma delas estiver relacionada à turma onde o turno foi modificado, e ao clicar, você for direcionado diretamente para a turma com as pendências, o teste é bem-sucedido. Caso contrário, considere o teste como falho.

## Migrations Utilizadas

## Checklist de revisão
- [x] O número da versão foi alterado no arquivo ``` config.php ```?
- [x] Foi adicionada uma descrição das alterações no arquivo de   ``` CHANGELOG ```?
- [x] O pull request passou na avaliação do SonarLint?
- [x] O pull request está nomeado corretamente seguindo o padrão de nomes de branchs?

2024-04-19 13:02 UTC, Gusta-Santos reviewed
Nos meus testes, a inconsistência foi evidênciada com sucesso, porém o redirecionamento ao clicar na inconsistência não funcionou

2024-04-20 23:11 UTC, AnotherOne07 approved these changes
✅ Fluxo de Teste realizado com sucesso: As turmas com inconsistências em relação ao turno estão sendo listadas na tabela, apresentando a descrição adequada.

❌ Fluxo de teste falhou: Ao clicar no link para ser redirecionado para a página da turma, o redirecionamento não é realizado adequadamente, a aplicação simplesmente atualiza a página.

2024-04-20 23:13 UTC, AnotherOne07 requested changes
✅ Fluxo de Teste realizado com sucesso: As turmas com inconsistências em relação ao turno estão sendo listadas na tabela, apresentando a descrição adequada.

❌ Fluxo de teste falhou: Ao clicar no link para ser redirecionado para a página da turma, o redirecionamento não é realizado adequadamente, a aplicação simplesmente atualiza a página.

2024-04-22 18:10 UTC, AnotherOne07 approved these changes
✅ Problema relatado na review anterior devidamente corrigido após rodar uma migration na tabela de inconsistency_sagres.

👍🏾 LGTM

2024-04-23 13:42 UTC, Gusta-Santos approved these changes
Deu tudo certo com os fluxos de teste

2024-04-25 18:45 UTC, merged