[TCDA-214] Feat/class plan validate
ipti/br.tag pull request #694
Opened 2024-04-21 22:11 UTC by AnotherOne07

## Motivação
- A tarefa consiste em desenvolver uma funcionalidade adicional para a tela de plano de aula. Essa nova alteração deve incluir um mecanismo de “aprovação de plano de aula” para um usuário do tipo “Coordenador Pedagógico”.

## Alterações Realizadas
### Telas:

- Criar Plano de aula:
    - Adicionar Input “Data Inicial” (Create finalizado)
    - Validação de que o plano está “disponível para edição”, o que em termos técnicos, signifca que o campo “situation” do plano está com o valor “PENDENTE”.
- (Novo) Criar Tela “Planos de Aula Pendentes”
    - Nesta tela, deve conter uma lista com os planos de aula criados pelos professores que estão com o seu status de aprovação como “Pendente”.
    - O acesso a cada plano deve ser semelhante ao acesso da listagem normal de plano de aula, no entanto, nesse caso deve ser possível aprovar um plano ou adicionar observações para revisão.

## 🧪  Fluxos de Teste

### 🧪 Fluxo de Teste 1: Criar Plano de Aula 

### 🧪 Fluxo de Teste 2: Validar plano de aula

### 🧪 Fluxo de Teste 3: Liberar Plano de Aula para edição

## Migrations Utilizadas
-

## Checklist de revisão
- [ ] O número da versão foi alterado no arquivo ``` config.php ```?
- [ ] Foi adicionada uma descrição das alterações no arquivo de   ``` CHANGELOG ```?
- [ ] O pull request passou na avaliação do SonarLint?
- [ ] O pull request está nomeado corretamente seguindo o padrão de nomes de branchs?

2024-04-22 19:52 UTC, nathanipti requested changes
### ✅ `🧪 Test 01 `
Plano de aula criado com sucesso

---
### ✅⚠️ `🧪 Test 02`

Obs.: Nesta tela, na minha opinião, era para mostrar apenas os planos de aulas marcados como aprovados. Está sendo mostrando os aprovados e não aprovados. 

Neste exemplo, o PLANO 02 não foi marcado ainda, mas está sendo mostrado.

![Screenshot 2024-04-22 155145](https://github.com/ipti/br.tag/assets/117388330/d3f4bf85-1854-4121-9bdc-827c420975a3)

---

⚠️ Ao acessar tela de planos de aula pendentes, é mostrado um popup para datatables:

![Screenshot 2024-04-22 160005](https://github.com/ipti/br.tag/assets/117388330/dc2cd01c-18e6-46dc-b6fb-a109c7de371c)

❌ A data inicial está ficando errada:

![Screenshot 2024-04-22 160658](https://github.com/ipti/br.tag/assets/117388330/c609749a-af67-47ea-85f7-d3740ee51ad5)


✅ Com relação ao fluxo de test, tudo certo.

---
### ✅ ### `🧪 Test 03`

Obs.: na descrição do teste 3, está assim: 
`deve clicar no botão "Liberar para Edição" disponível na coluna de "Ações"`

Não identifiquei o botão: "Liberar para Edição". Cliquei no icone de editar e foi.

Se for esse o icon, acho melhor mudar para algo que remeta melho uma ação de Liberação.

✅ Test 03 passou com sucesso!

---
✅ ### `🧪 Test 04`

No teste 04, ao não marcar o checkbox de "Aprovação do plano" e clicar em "Salvar aprovação", deveria ser mostrado uma msg de sucesso.

### Obs.: 
Fica disponível apenas o campo de Nome e Data Inicial para edição. É para ficar apenas esses 2 campos?

2024-04-22 19:57 UTC, GabrielChagas14 reviewed
Após aprovar um plano de aula com o perfil de coordenador a data salva para o início do plano é perdida ao acessar o plano como professor como segue  no caso de teste abaixo
criando plano como professor:
![image](https://github.com/ipti/br.tag/assets/84946326/65f2ddf4-60b2-4aaf-8dd3-a90b61a2a909)
aprovando plano como coordenador
![image](https://github.com/ipti/br.tag/assets/84946326/bb1bcb2c-0eff-40a0-8d0c-895d073000e3)
acessando o plano como professor novamente
![image](https://github.com/ipti/br.tag/assets/84946326/6ee30326-f000-4ced-96cf-1837f35d8b02)

coordenador consegue editar o nome e a data de início do plano de aula

![image](https://github.com/ipti/br.tag/assets/84946326/91704bc4-55ec-44a3-a7d6-92197ff29585)

coordenador tem acesso para criar plano de aula

![image](https://github.com/ipti/br.tag/assets/84946326/493d5854-9046-4a77-a350-252a2c7601d8)

2024-04-23 15:02 UTC, GabrielChagas14 approved these changes
LGTM

2024-04-24 20:27 UTC, nathanipti approved these changes
Todos os testes foram realizados com sucesso!

2024-04-26 19:10 UTC, merged