Feat/reuse structure
ipti/br.tag pull request #881
Opened 2024-11-29 11:59 UTC by GabrielChagas14

## Motivação

## Alterações Realizadas

## Fluxo de Teste

## Migrations Utilizadas

## Checklist de revisão
- [ ] O número da versão foi alterado no arquivo ``` config.php ```?
- [ ] Foi adicionada uma descrição das alterações no arquivo de   ``` CHANGELOG ```?
- [ ] O pull request passou na avaliação do SonarLint?
- [ ] O pull request está nomeado corretamente seguindo o padrão de nomes de branchs?

2025-01-17 16:03 UTC, AnotherOne07 requested changes
🧪 Review feat/reuse-structure:

Teste 1: ❌ Erro (Logo após rodar a migration, divisão por zero)
Teste 2: ❌ Erro (Logo após rodar a migration, divisão por zero)
Teste 3: ❌ Erro (Logo após rodar a migration, divisão por zero)
Teste 4: ✅ Sucesso
Teste 5: ❌ Erro (Após criar a estrutura, atualizar em configurações pedagógicas, divisão por zero)
Teste 6: ❌ Erro (Após criar a estrutura, atualizar em configurações pedagógicas, select de estrutura de notas com valores duplicados, select de unidades vazio na tela de notas) 

Atualização muito boa, agrega muito à experiência do usuário nessa tela, além disso, acredito que torna a funcionalidade mais confiável, o que aumenta a qualidade de nosso sistema.

💡 Dúvidas:

Poderia me explicar o porque da decisão de criar uma tabela N:N entre classroom e grade_rules?

🗒️ Log:
- Logo após rodar a migration em um banco atualizado (17/01/2025) de muribeca, o registro das notas persistiu mas ao tentar salvar as notas a api retornou um erro de divisão por 0. Acredito que esteja relacionado ao fato de que ainda não foi atribuído nenhum registro a "ESTRUTURA DE NOTAS" após a atualização da regra. O erro ocorreu tanto para nota numérica quanto para nota por conceito.

- Após criar uma estrutura de notas numérica, selecionar a etapa e alterar o valor na tela de Configurações Pedagógicas o cálculo está funcionando adequadamente.

- Após criar uma estrutura de notas por conceito, selecionar a etapa e alterar o valor na tela de Configurações pedagócias, a funcionalidade não está funcionando adequadamente, emitindo o erro de Divisão por Zero na requisição.

- Após criar a estrutura de notas para uma turma multi, salvar como estrutura de avaliação da turma multi, ao acessar a tela de edição da turma, encontrei o select com valores duplicados.

- Após atribuir a estrutura de avaliação da turma e de cada etapa, ao acessar a tela de grades o select de unidades está vazio, tanto para o caso de uma turma com notas por conceito quanto para o caso de uma turma com notas numéricas.

2025-01-24 14:45 UTC, GabrielChagas14 commented
> 🧪 Review feat/reuse-structure:
> 
> Teste 1: ❌ Erro (Logo após rodar a migration, divisão por zero) Teste 2: ❌ Erro (Logo após rodar a migration, divisão por zero) Teste 3: ❌ Erro (Logo após rodar a migration, divisão por zero) Teste 4: ✅ Sucesso Teste 5: ❌ Erro (Após criar a estrutura, atualizar em configurações pedagógicas, divisão por zero) Teste 6: ❌ Erro (Após criar a estrutura, atualizar em configurações pedagógicas, select de estrutura de notas com valores duplicados, select de unidades vazio na tela de notas)
> 
> Atualização muito boa, agrega muito à experiência do usuário nessa tela, além disso, acredito que torna a funcionalidade mais confiável, o que aumenta a qualidade de nosso sistema.
> 
> 💡 Dúvidas:
> 
> Poderia me explicar o porque da decisão de criar uma tabela N:N entre classroom e grade_rules?
> 
> 🗒️ Log:
> 
>     * Logo após rodar a migration em um banco atualizado (17/01/2025) de muribeca, o registro das notas persistiu mas ao tentar salvar as notas a api retornou um erro de divisão por 0. Acredito que esteja relacionado ao fato de que ainda não foi atribuído nenhum registro a "ESTRUTURA DE NOTAS" após a atualização da regra. O erro ocorreu tanto para nota numérica quanto para nota por conceito.
> 
>     * Após criar uma estrutura de notas numérica, selecionar a etapa e alterar o valor na tela de Configurações Pedagógicas o cálculo está funcionando adequadamente.
> 
>     * Após criar uma estrutura de notas por conceito, selecionar a etapa e alterar o valor na tela de Configurações pedagócias, a funcionalidade não está funcionando adequadamente, emitindo o erro de Divisão por Zero na requisição.
> 
>     * Após criar a estrutura de notas para uma turma multi, salvar como estrutura de avaliação da turma multi, ao acessar a tela de edição da turma, encontrei o select com valores duplicados.
> 
>     * Após atribuir a estrutura de avaliação da turma e de cada etapa, ao acessar a tela de grades o select de unidades está vazio, tanto para o caso de uma turma com notas por conceito quanto para o caso de uma turma com notas numéricas.

A tabela foi criada porque uma mesma turma pode ter mais de uma estrutura associada a ela, como é o caso das turmas multisseriadas, e um grade_rules pode ser associado a várias turmas.

2025-01-28 15:16 UTC, AnotherOne07 requested changes
⚠️ Teste 1:
- Notas salvas com sucesso, no entanto, é preciso salvar a estrutura de notas da etapa uma vez após rodar a migration para conseguir salvar as notas.

⚠️ Teste 2:
- Após rodar a migration, na tela de grades, o select das unidades fica com as options duplicadas.  Salvamento de notas funciona, no entanto, é necessário averiguar situação do select apresentando options duplicadas.

⚠️ Teste 3:
- Após rodar a migration e salvar uma vez a estrutura e o form de atualizar turma, sem alterar nenhuma informação na aba de configurações pedagógicas. As notas foram salvas com sucesso.

✅ Teste 4
- Notas calculadas com sucesso.

✅ Teste 5
- Notas calculadas com sucesso.

⚠️  Teste 6
- Ao atribuir uma estrutura de notas por conceito a uma das etapas da turma MULTI, o valor atribuído não está persistindo após salvar. Ao acessar a tela de notas, e tentar salvar as notas de uma etapa com estrutura de notas numérico, está salvando mas o retorno da requisição está informando que houve algum erro durante a execução da rota da API.

2025-02-07 15:38 UTC, AnotherOne07 approved these changes
👍🏾 LGTM

2025-02-12 14:10 UTC, Gusta-Santos approved these changes
LGTM

2025-02-19 17:18 UTC, joannestephany commented
Nota: Implementação de uma funcionalidade para melhorar a forma como os municípios cadastram e gerenciam estruturas educacionais com múltiplas etapas.

**Melhorias**
- Cadastro de Estruturas Compartilhadas : Agora, os municípios podem criar uma única estrutura educacional de etapa numérica ou por conceito e aplicá-la a várias turmas que compartilham a mesma configuração.
- Flexibilização da Reutilização Anual: Antes, os municípios eram obrigados a reutilizar as mesmas estruturas educacionais a cada ano. Agora, essa limitação foi resolvida, permitindo ajustes sem impactar dados antigos.

2025-02-19 18:40 UTC, joannestephany commented
Por favor, informar junto a PR, caso a atualização enviada demande de atualização no manual de uso do sistema. 

@GabrielChagas14

2025-02-26 12:45 UTC, merged